//RECUPERAR O BOTÃO E COLOCAR ELE EM UMA CONSTANTE 
const botaoSubmit = document.getElementById('btnEnviar')

//ATRELAR UM EVENTO AO BOTÃO PARA QUE AO SER DISPARADO O EVENTO CLICK 
//OS CAMPOS/INPUTS SEJAM VALIDADOS(VERIFICADOS SE ESTÃO VAZIOS)
botaoSubmit.addEventListener('click', )
